sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - pip install gifmaze

script:
  - cd examples; for f in example*.py; do python -m unittest "$f"; done

cashe: pip
